### ISSUE TITLE
这个框架有内存泄露

### ISSUE THREAD

**Issue by hw20101101** [qiniu/happy-dns-objc#12]
附上图片：
[http://7xqvz3.com1.z0.glb.clouddn.com/201603QQ20160307-0.png](url)

**Comment by hw20101101** [comment]
github居然无法打开七牛的图片链接，你们在浏览器上新开一个窗口，把上面的图片链接拷过去就能看到了。

**Comment by longbai** [comment]
囧，这个 不是 内存 泄露。。。 我下一版改下

**Comment by hw20101101** [comment]
哦，好的
