### ISSUE TITLE
QNConfigurationBuilder里dns属性为assign导致不能自定义dns

### ISSUE THREAD

**Issue by pengbeicn** [qiniu/happy-dns-objc#15]
我在使用initWithConfiguration创建QNUploadManager时传入了QNConfiguration，但是运行时崩溃了，原因是是QNConfigurationBuilder里dns属性为assign导致。

**Comment by longbai** [comment]
？ 没懂，能贴下代码么。 这个本来就应该是assign啊

**Comment by pengbeicn** [comment]
我在创建QNConfiguration实例的时候，设置builder.dns时，xcode会有警告，而且在使用builder.dns的时候会有崩溃异常
    QNConfiguration* conf = [QNConfiguration build:^(QNConfigurationBuilder *builder) {
        id<QNResolverDelegate> r1 = [QNResolver systemResolver];
        id<QNResolverDelegate> r2 = [[QNResolver alloc] initWithAddres:@"119.29.29.29"];
        id<QNResolverDelegate> r3 = [[QNResolver alloc] initWithAddres:@"114.114.115.115"];
        
        builder.dns = [[QNDnsManager alloc] init:[NSArray arrayWithObjects:r1,r2,r3,nil] networkInfo:[QNNetworkInfo normal]];
    }];
    QNUploadManager *upManager = [[QNUploadManager alloc] initWithConfiguration:conf];

**Comment by longbai** [comment]
不明白，我这里编译没有警告 xcode 7.3, 也没有崩溃，单元测试都正常。崩溃的日志 以及警告麻烦都贴下好么？

**Comment by pengbeicn** [comment]
不好意思，我刚才更新了一下Pod，发现QNConfigurationBuilder里dns已经去掉了assign属性，麻烦了！

**Comment by pengbeicn** [comment]
该项目本身代码不会崩溃，但是当我在配置自定义dns时会崩溃，原因是QNConfiguration里的dns属性为(nonatomic, readonly)，但是QNConfigurationBuilder里的dns的属性为(nonatomic, assign)，这就导致了在设置dns时，对象没有保存，而是立即释放掉了，下面是我在使用上传文件QNUploadManager的代码：

`QNConfiguration* conf = [QNConfiguration build:^(QNConfigurationBuilder *builder) {`
`    id<QNResolverDelegate> r1 = [QNResolver systemResolver];`
`    id<QNResolverDelegate> r2 = [[QNResolver alloc] initWithAddres:@"119.29.29.29"];`
`    id<QNResolverDelegate> r3 = [[QNResolver alloc] initWithAddres:@"114.114.115.115"];`
`    builder.dns = [[QNDnsManager alloc] init:[NSArray arrayWithObjects:r1,r2,r3,nil] networkInfo:[QNNetworkInfo normal]];`
`}];`
`QNUploadManager *upManager = [[QNUploadManager alloc] initWithConfiguration:conf];`

**Comment by longbai** [comment]
已经改了 https://github.com/qiniu/objc-sdk/pull/142
