### ISSUE TITLE
localdns模式 有demo吗？

### ISSUE THREAD

**Issue by li6185377** [qiniu/happy-dns-objc#27]
有点看不懂 readme 里面的内容

**Comment by longbai** [comment]
哦，可以参考单元测试的内容

**Comment by li6185377** [comment]
能具体说下 单元测试里面的  哪个文件  哪个方法吗？

**Comment by longbai** [comment]
https://github.com/qiniu/happy-dns-objc/blob/master/HappyDNSTests/DnsTest.m#L37
