### ISSUE TITLE
分享happy-dns 配合 SDWebImage 的使用

### ISSUE THREAD

**Issue by iTA9178** [qiniu/happy-dns-objc#3]
1.先pod 'HappyDNS', '~> 0.1.1'到项目中；

2.项目中使用QNDnsManager 返回ips;
    NSMutableArray *array = [[NSMutableArray alloc]init];
    [array addObject:[QNResolver systemResolver]];
    [array addObject:[[QNResolver alloc] initWithAddres:@"114.114.115.115"]];
    QNDnsManager *dnsManager = [[QNDnsManager alloc] init:array networkInfo:[QNNetworkInfo normal]];
    NSArray *ips = [dnsManager query:@"http://xxxx.com2.z0.glb.qiniucdn.com"];

3.请求七牛图片时使用ip替换域名http://xxxx.com2.z0.glb.qiniucdn.com，并设置HTTPHeadField;
[SDWebImageManager.sharedManager.imageDownloader setValue:@"http://xxxx.com2.z0.glb.qiniucdn.com" forHTTPHeaderField:@"Host"];
注：自己封装请求图片时使用[request setValue: @"http://xxxx.com2.z0.glb.qiniucdn.com" forHTTPHeaderField:@"Host"];

4.项目中因为图片还有其他来源，这里区分使用设置HTTPHeadField中Host;
SDWebImageManager.sharedManager.imageDownloader.headersFilter  = ^NSDictionary *(NSURL *url, NSDictionary *headers)
    {
        NSMutableDictionary *mutableHeaders = [headers mutableCopy];
        [mutableHeaders removeObjectForKey:@"Host"];
        //是否为ip格式
        if ([url.host rh_isIp])
        {
            [mutableHeaders setValue:@"xxxx.com2.z0.glb.qiniucdn.com" forKey:@"Host"];
        }
        return mutableHeaders;
    };

最后，谢谢longbai在此过程中提供的帮助，由于缺少相关文档，冒昧抛砖引玉，希望可以帮助到小伙伴们，欢迎一起交流！

**Comment by longbai** [comment]
@iTA9178 十分感谢啊，这个地方 还有可以优化的地方 就是使用NSURLProtocol 这样代码会更干净些，另外可以对这些IP 进行挨个重试，假如一个失败 就切换到下一个

**Comment by neil-wu** [comment]
您好，有个问题想咨询一下。
我的项目在七牛里使用了自定义域名 pics.imheyo.cn ，我使用HappyDNS把域名的解析结果IP来访问图片，会加载不到图片。
比如 http://pics.imheyo.cn/00dc9679aaf3536832bc7e25cb0f9653 （原链接 http://7xoe2h.com2.z0.glb.qiniucdn.com/00dc9679aaf3536832bc7e25cb0f9653 ）
域名解析 pics.imheyo.cn 的结果为 36.42.32.254， 使用 http://36.42.32.254/00dc9679aaf3536832bc7e25cb0f9653 则会访问失败。

请问，域名解析的结果是不是不能直接使用呢？

**Comment by longbai** [comment]
@neil-wu  需要设置 Host header

**Comment by neil-wu** [comment]
@longbai  多谢。
请问是设置为 [mutableHeaders setValue:@"xxxx.com2.z0.glb.qiniucdn.com" forKey:@"Host"];
还是使用IP来设置呢  [mutableHeaders setValue:@"36.42.32.254" forKey:@"Host"];

我用IP来设置，报错 NSURLErrorDomain Code=400

**Comment by longbai** [comment]
... use domain to set

**Comment by neil-wu** [comment]
@longbai  明白啦，多谢多谢。已经可以了
