### ISSUE TITLE
happy-dns可以和afnetworking配合使用吗

### ISSUE THREAD

**Issue by lyzhang1999** [qiniu/happy-dns-objc#37]
happy-dns可以和afnetworking配合使用吗？目前我们在联通3/4g网发现无法查找主机的问题，已经确定是dns的问题所以我们想在afnetworking使用httpdns，不知道是不是能够兼容？

**Comment by longbai** [comment]
可以，我们的sdk 已经整合，但如果使用联通的代理 就不能用
