### ISSUE TITLE
query到的结果有时候是空字符串

### ISSUE THREAD

**Issue by HoneyLuka** [qiniu/happy-dns-objc#41]
在某些用户的手机上出现的这种情况，query返回的array里包含空字符串。我自己没对结果做太多判断结果坑了。。

**Comment by HoneyLuka** [comment]
HappyDns是不是可以对结果做一些check会比较好

**Comment by longbai** [comment]
嗯，我看下，有详细的日志么？

**Comment by HoneyLuka** [comment]
这个其实就是我用来将URL的host替换成IP，然后因为IP是空字符串，所以最终生成出来URL是个错误的url，然后webview提示找不到网页
