### ISSUE TITLE
导入SDK编译出错

### ISSUE THREAD

**Issue by charsdavy** [qiniu/happy-dns-objc#42]
自己的工程，不想使用cocoapods，所以将sdk导入工程，结构如下：
![struct](https://cloud.githubusercontent.com/assets/13601929/17806293/396e836e-6636-11e6-9d36-19c685aaf353.png)
编译出错，提示如下：
![error_1](https://cloud.githubusercontent.com/assets/13601929/17806294/396ea858-6636-11e6-8bd7-e83cec88ebf9.png)
![error_2](https://cloud.githubusercontent.com/assets/13601929/17806295/396f06c2-6636-11e6-8500-a1eadfb5fe96.png)
是否因为没有导入某些第三方框架？
能够加入单独使用七牛sdk的方法，不依赖于cocoapods。
谢谢！

**Comment by charsdavy** [comment]
已经解决了。

**Comment by longbai** [comment]
需要导入 libz, libresolv
