### ISSUE TITLE
在 QNGetAddrInfo.m 中导入系统库时的写法有点问题

### ISSUE THREAD

**Issue by cgwangding** [qiniu/happy-dns-objc#46]
导入系统库时"#include "string.h" " 这种写法是不规范的，应该修改为 "#include <string.h>"，后面的两个也一样。
使用了第一种写法，如果有第三方库中定义了string.h 文件的话，两个库在一起很可能就会报错。

当然，我在这里提这个问题正式因为我们在使用 grpc的时候遇到这个尴尬的问题。所以，为了以后同学能够更好的使用，希望你们能够采纳我的建议，修改掉代码里的这种用法。
 
期待你们的回复

**Comment by longbai** [comment]
fixed in 0.3.11
