### ISSUE TITLE
请问支持自定义dns解析的ip么？

### ISSUE THREAD

**Issue by seaguest** [qiniu/happy-dns-objc#76]
Hi,

```
NSURL *u2 = [dns queryAndReplaceWithIP:u];
```
这里能外部指定ip么？我的服务端会下发不同的ip，希望直接在客户端请求的时候直接使用下发的ip（而不是通过dns解析出来的ip），不知道该怎么实现呢？

**Comment by seaguest** [comment]
putHosts方法可以实现我的目标么？

**Comment by YangSen-qn** [comment]
@seaguest 

> putHosts方法可以实现我的目标么？

满足你的需求，不过在 dns 解析的时候，需要指定先查询 host 配置(hostsFirst 为 true)，如下：
```
QNDomain *domain = [[QNDomain alloc] init:@"domain" hostsFirst:YES hasCname:NO];
```

**Comment by seaguest** [comment]
谢谢！
